import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { browser } from "process";

const inter = Inter({ subsets: ["latin"] });

export async function getServerSideProps() {
  const userRequest = await (
    await fetch("https://jsonplaceholder.typicode.com/users")
  ).json();
  // const userData = await userRequest.json();
  console.log(userRequest);
  return {
    props: {
      users: userRequest,
    },
  };
}
export default function Home(props: any) {
  const side = typeof window ? "client's" : "server's";

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <p>
          {props.users.map((m: any) => (
            <div>
              <p>{m.email}</p>
              <p>{m.username}</p>
            </div>
          ))}
        </p>
        <div>You're currently on the {side}-sides</div>
      </main>
    </>
  );
}
